#!/bin/bash

# set minimize click on ubuntu dock 
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'

# update
sudo apt-get update
sudo apt-get upgrade -y

# add repos
sudo add-apt-repository -y ppa:papirus/papirus
sudo add-apt-repository -y ppa:tista/adapta
sudo add-apt-repository -y ppa:system76/pop

# update repos again
sudo apt update

# install apps
sudo apt-get install -y steam hexchat arc-theme chrome-gnome-shell gnome-tweak-tool adapta-gtk-theme neofetch streamlink mpv vlc docker-ce nautilus-dropbox zsh curl pop-fonts

# install snap packages
sudo snap install slack --classic
sudo snap install discord spotify

# add user to docker group
sudo usermod -aG docker $USER

#change shell to zsh
chsh -s $(which zsh)

# run oh my zsh install script
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# reboot
echo "If you see this reboot, you reached the end of the script"
