#!/bin/bash

# add repos
sudo add-apt-repository -y ppa:numix/ppa
sudo add-apt-repository -y ppa:atareao/atareao
sudo add-apt-repository -y ppa:webupd8team/java
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo add-apt-repository -y ppa:yorba/ppa
sudo add-apt-repository -y ppa:skunk/pepper-flash
# update
sudo apt-get update
sudo apt-get upgrade

# install apps
sudo apt-get install steam hexchat numix-gtk-theme skype unity-tweak-tool my-weather-indicator vlc gdebi oracle-java8-installer compizconfig-settings-manager gtk2-engines-murrine:i386 gtk2-engines-pixbuf:i386 p7zip numix-icon-theme-circle numix-icon-theme git steam-skin-manager gtk-redshift geary pepflashplugin-installer

# restricted extras
sudo apt-get install -y ubuntu-restricted-extras

# reboot
echo "You should probably reboot or something"
